export const FORM_PROJECT = "FORM_PROJECT";
export const GET_PROJECTS = "GET_PROJECTS";
export const ADD_PROJECTS = "ADD_PROJECTS";
export const VALIDATE_FORM = "VALIDATE_FORM";
export const PROJECT_SELECTED = "PROJECT_SELECTED";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const TASKS_PROJECT = "TASKS_PROJECT";
export const ADD_TASK = "ADD_TASK";
export const DELETE_TASK = "DELETE_TASK";
export const CHANGE_STATE_TASK = "CHANGE_STATE_TASK";
export const ACTUAL_TASK = "ACTUAL_TASK";
export const EDIT_TASK = "EDIT_TASK";

